name: Snapshot Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  snapshot-tests:
    name: Run Snapshot Tests
    runs-on: macos-14
    
    strategy:
      matrix:
        xcode: ['15.2']
        simulator: ['iPhone 15 Pro']
        ios: ['17.2']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true  # Enable Git LFS if using it for snapshots
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      
      - name: Show Xcode version
        run: xcodebuild -version
      
      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: List available simulators
        run: xcrun simctl list devices available
      
      - name: Boot simulator
        run: |
          SIMULATOR_ID=$(xcrun simctl list devices available | grep "${{ matrix.simulator }}" | head -n 1 | sed 's/.* (\([^)]*\)).*/\1/')
          echo "Booting simulator: $SIMULATOR_ID"
          xcrun simctl boot "$SIMULATOR_ID" || true
          
          # Set simulator to light mode for consistent snapshots
          xcrun simctl ui "$SIMULATOR_ID" appearance light
      
      - name: Build for testing
        run: |
          xcodebuild build-for-testing \
            -scheme SportsAppClone \
            -destination 'platform=iOS Simulator,name=${{ matrix.simulator }},OS=${{ matrix.ios }}' \
            -derivedDataPath DerivedData \
            | xcbeautify || true
      
      - name: Run snapshot tests
        run: |
          xcodebuild test-without-building \
            -scheme SportsAppClone \
            -destination 'platform=iOS Simulator,name=${{ matrix.simulator }},OS=${{ matrix.ios }}' \
            -derivedDataPath DerivedData \
            -only-testing:SportsAppCloneTests/GameCardViewSnapshotTests \
            -only-testing:SportsAppCloneTests/LeagueFilterViewSnapshotTests \
            -only-testing:SportsAppCloneTests/FavoritesViewSnapshotTests \
            -only-testing:SportsAppCloneTests/GamesListViewSnapshotTests \
            | xcbeautify || true
        continue-on-error: true
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.simulator }}-${{ matrix.ios }}
          path: |
            DerivedData/Logs/Test/*.xcresult
          retention-days: 30
      
      - name: Check for snapshot failures
        if: always()
        run: |
          if [ -d "Tests/SnapshotTests/__Snapshots__" ]; then
            FAILURE_COUNT=$(find Tests/SnapshotTests/__Snapshots__ -name "Failure*" | wc -l)
            echo "Found $FAILURE_COUNT snapshot failures"
            
            if [ $FAILURE_COUNT -gt 0 ]; then
              echo "::error::Snapshot tests failed! Found $FAILURE_COUNT mismatched snapshots."
              exit 1
            fi
          fi
      
      - name: Upload failed snapshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-snapshots-${{ matrix.simulator }}-${{ matrix.ios }}
          path: |
            Tests/SnapshotTests/__Snapshots__/**/Failure/**
          retention-days: 7
      
      - name: Comment PR with snapshot failures
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const snapshotDir = 'Tests/SnapshotTests/__Snapshots__';
            let failureMessage = '## ⚠️ Snapshot Test Failures\n\n';
            failureMessage += 'The following snapshot tests failed:\n\n';
            
            // Find all failure directories
            const findFailures = (dir) => {
              const failures = [];
              if (fs.existsSync(dir)) {
                const items = fs.readdirSync(dir, { withFileTypes: true });
                for (const item of items) {
                  const fullPath = path.join(dir, item.name);
                  if (item.isDirectory()) {
                    if (item.name.includes('Failure')) {
                      failures.push(fullPath);
                    }
                    failures.push(...findFailures(fullPath));
                  }
                }
              }
              return failures;
            };
            
            const failures = findFailures(snapshotDir);
            
            if (failures.length > 0) {
              failureMessage += `- ${failures.length} snapshot(s) failed\n\n`;
              failureMessage += '### Actions to take:\n';
              failureMessage += '1. Review the uploaded artifacts to see the differences\n';
              failureMessage += '2. If changes are intentional, run tests locally with `SNAPSHOT_TESTING_RECORD=1`\n';
              failureMessage += '3. Commit the updated snapshots\n';
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: failureMessage
              });
            }

  unit-tests:
    name: Run Unit Tests
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      
      - name: Run unit tests
        run: |
          xcodebuild test \
            -scheme SportsAppClone \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            -only-testing:SportsAppCloneTests/SportsViewModelTests \
            -only-testing:SportsAppCloneTests/SportModelTests \
            -only-testing:SportsAppCloneTests/SportsDataServiceTests \
            | xcbeautify || true
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: |
            DerivedData/Logs/Test/*.xcresult
          retention-days: 30

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [snapshot-tests, unit-tests]
    if: always()
    
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.snapshot-tests.result }}" == "failure" ] || [ "${{ needs.unit-tests.result }}" == "failure" ]; then
            echo "::error::Tests failed!"
            exit 1
          else
            echo "✅ All tests passed!"
          fi
